### ISSUE TITLE
FoV changer no longer works on the latest version

### ISSUE THREAD

**Issue by glencoe2004** [SeanPesce/DXMD-FoV-Changer#4]
File Ver: 1.19.801.0

The game doesn't crash, but the changer does nothing. Pressing key combos does not change fov or beep, and the .INI does not change FOV (I think).

**Comment by SeanPesce** [comment]
I just tested [this release](https://github.com/SeanPesce/DXMD-FoV-Changer/releases/tag/2018-03-27) with the latest version of the game (1.19.801.0, Windows 10, Steam) and it seems to work. Are you sure it's installed correctly? The DLL and .ini should be placed in the `Deus Ex Mankind Divided\retail` directory. The default keybinds are `+` and `-` to change the FoV.

**Comment by SeanPesce** [comment]
If anyone else encounters this issue, please comment here with your game version, operating system, and platform (Steam, GoG, etc.).

**Comment by SeanPesce** [comment]
It appears that the DLL won't be loaded by the latest GoG release when the game is launched directly through `DXMD.exe`. The DLL should work if the game is launched through GoG Galaxy.

**Note:** I haven't actually tested whether the memory patches work with the GoG version yet. I'll have to look into it.

**Comment by domportera** [comment]
the FOV changer works for me on the gog launcher.

there might be some user error here, or it just genuinely doesnt work for some people. for me, i know that customizing keybinds took a few tries because I didnt realize I needed to use the hex codes AND needed to remove the leading 0x (though the default assignments should have given me that hint)

**Comment by SeanPesce** [comment]
Thanks for the information! Today I [updated the mod](https://github.com/SeanPesce/DXMD-FoV-Changer/releases) to support the GoG build with **or** without the GoG launcher. I believe the mod now supports all the latest versions on Windows.

**Comment by domportera** [comment]
thank you for continuing to keep up with this :) some of us are late to the party
